<?php return array (
    'AFN' => array (
        'alphabeticCode' => 'AFN',
        'currencyName' => 'Afghani',
        'fractionDigits' => 2,
        'numericCode' => '971',
    ),
    'EUR' => array (
        'alphabeticCode' => 'EUR',
        'currencyName' => 'Euro',
        'fractionDigits' => 2,
        'numericCode' => '978',
    ),
    'ALL' => array (
        'alphabeticCode' => 'ALL',
        'currencyName' => 'Lek',
        'fractionDigits' => 2,
        'numericCode' => '8',
    ),
    'DZD' => array (
        'alphabeticCode' => 'DZD',
        'currencyName' => 'Algerian Dinar',
        'fractionDigits' => 2,
        'numericCode' => '12',
    ),
    'USD' => array (
        'alphabeticCode' => 'USD',
        'currencyName' => 'US Dollar',
        'fractionDigits' => 2,
        'numericCode' => '840',
    ),
    'AOA' => array (
        'alphabeticCode' => 'AOA',
        'currencyName' => 'Kwanza',
        'fractionDigits' => 2,
        'numericCode' => '973',
    ),
    'XCD' => array (
        'alphabeticCode' => 'XCD',
        'currencyName' => 'East Caribbean Dollar',
        'fractionDigits' => 2,
        'numericCode' => '951',
    ),
    'ARS' => array (
        'alphabeticCode' => 'ARS',
        'currencyName' => 'Argentine Peso',
        'fractionDigits' => 2,
        'numericCode' => '32',
    ),
    'AMD' => array (
        'alphabeticCode' => 'AMD',
        'currencyName' => 'Armenian Dram',
        'fractionDigits' => 2,
        'numericCode' => '51',
    ),
    'AWG' => array (
        'alphabeticCode' => 'AWG',
        'currencyName' => 'Aruban Florin',
        'fractionDigits' => 2,
        'numericCode' => '533',
    ),
    'AUD' => array (
        'alphabeticCode' => 'AUD',
        'currencyName' => 'Australian Dollar',
        'fractionDigits' => 2,
        'numericCode' => '36',
    ),
    'AZN' => array (
        'alphabeticCode' => 'AZN',
        'currencyName' => 'Azerbaijan Manat',
        'fractionDigits' => 2,
        'numericCode' => '944',
    ),
    'BSD' => array (
        'alphabeticCode' => 'BSD',
        'currencyName' => 'Bahamian Dollar',
        'fractionDigits' => 2,
        'numericCode' => '44',
    ),
    'BHD' => array (
        'alphabeticCode' => 'BHD',
        'currencyName' => 'Bahraini Dinar',
        'fractionDigits' => 3,
        'numericCode' => '48',
    ),
    'BDT' => array (
        'alphabeticCode' => 'BDT',
        'currencyName' => 'Taka',
        'fractionDigits' => 2,
        'numericCode' => '50',
    ),
    'BBD' => array (
        'alphabeticCode' => 'BBD',
        'currencyName' => 'Barbados Dollar',
        'fractionDigits' => 2,
        'numericCode' => '52',
    ),
    'BYN' => array (
        'alphabeticCode' => 'BYN',
        'currencyName' => 'Belarusian Ruble',
        'fractionDigits' => 2,
        'numericCode' => '933',
    ),
    'BZD' => array (
        'alphabeticCode' => 'BZD',
        'currencyName' => 'Belize Dollar',
        'fractionDigits' => 2,
        'numericCode' => '84',
    ),
    'XOF' => array (
        'alphabeticCode' => 'XOF',
        'currencyName' => 'CFA Franc BCEAO',
        'fractionDigits' => 0,
        'numericCode' => '952',
    ),
    'BMD' => array (
        'alphabeticCode' => 'BMD',
        'currencyName' => 'Bermudian Dollar',
        'fractionDigits' => 2,
        'numericCode' => '60',
    ),
    'INR' => array (
        'alphabeticCode' => 'INR',
        'currencyName' => 'Indian Rupee',
        'fractionDigits' => 2,
        'numericCode' => '356',
    ),
    'BTN' => array (
        'alphabeticCode' => 'BTN',
        'currencyName' => 'Ngultrum',
        'fractionDigits' => 2,
        'numericCode' => '64',
    ),
    'BOB' => array (
        'alphabeticCode' => 'BOB',
        'currencyName' => 'Boliviano',
        'fractionDigits' => 2,
        'numericCode' => '68',
    ),
    'BOV' => array (
        'alphabeticCode' => 'BOV',
        'currencyName' => 'Mvdol',
        'fractionDigits' => 2,
        'numericCode' => '984',
    ),
    'BAM' => array (
        'alphabeticCode' => 'BAM',
        'currencyName' => 'Convertible Mark',
        'fractionDigits' => 2,
        'numericCode' => '977',
    ),
    'BWP' => array (
        'alphabeticCode' => 'BWP',
        'currencyName' => 'Pula',
        'fractionDigits' => 2,
        'numericCode' => '72',
    ),
    'NOK' => array (
        'alphabeticCode' => 'NOK',
        'currencyName' => 'Norwegian Krone',
        'fractionDigits' => 2,
        'numericCode' => '578',
    ),
    'BRL' => array (
        'alphabeticCode' => 'BRL',
        'currencyName' => 'Brazilian Real',
        'fractionDigits' => 2,
        'numericCode' => '986',
    ),
    'BND' => array (
        'alphabeticCode' => 'BND',
        'currencyName' => 'Brunei Dollar',
        'fractionDigits' => 2,
        'numericCode' => '96',
    ),
    'BGN' => array (
        'alphabeticCode' => 'BGN',
        'currencyName' => 'Bulgarian Lev',
        'fractionDigits' => 2,
        'numericCode' => '975',
    ),
    'BIF' => array (
        'alphabeticCode' => 'BIF',
        'currencyName' => 'Burundi Franc',
        'fractionDigits' => 0,
        'numericCode' => '108',
    ),
    'CVE' => array (
        'alphabeticCode' => 'CVE',
        'currencyName' => 'Cabo Verde Escudo',
        'fractionDigits' => 2,
        'numericCode' => '132',
    ),
    'KHR' => array (
        'alphabeticCode' => 'KHR',
        'currencyName' => 'Riel',
        'fractionDigits' => 2,
        'numericCode' => '116',
    ),
    'XAF' => array (
        'alphabeticCode' => 'XAF',
        'currencyName' => 'CFA Franc BEAC',
        'fractionDigits' => 0,
        'numericCode' => '950',
    ),
    'CAD' => array (
        'alphabeticCode' => 'CAD',
        'currencyName' => 'Canadian Dollar',
        'fractionDigits' => 2,
        'numericCode' => '124',
    ),
    'KYD' => array (
        'alphabeticCode' => 'KYD',
        'currencyName' => 'Cayman Islands Dollar',
        'fractionDigits' => 2,
        'numericCode' => '136',
    ),
    'CLP' => array (
        'alphabeticCode' => 'CLP',
        'currencyName' => 'Chilean Peso',
        'fractionDigits' => 0,
        'numericCode' => '152',
    ),
    'CLF' => array (
        'alphabeticCode' => 'CLF',
        'currencyName' => 'Unidad de Fomento',
        'fractionDigits' => 4,
        'numericCode' => '990',
    ),
    'CNY' => array (
        'alphabeticCode' => 'CNY',
        'currencyName' => 'Yuan Renminbi',
        'fractionDigits' => 2,
        'numericCode' => '156',
    ),
    'COP' => array (
        'alphabeticCode' => 'COP',
        'currencyName' => 'Colombian Peso',
        'fractionDigits' => 2,
        'numericCode' => '170',
    ),
    'COU' => array (
        'alphabeticCode' => 'COU',
        'currencyName' => 'Unidad de Valor Real',
        'fractionDigits' => 2,
        'numericCode' => '970',
    ),
    'KMF' => array (
        'alphabeticCode' => 'KMF',
        'currencyName' => 'Comorian Franc ',
        'fractionDigits' => 0,
        'numericCode' => '174',
    ),
    'CDF' => array (
        'alphabeticCode' => 'CDF',
        'currencyName' => 'Congolese Franc',
        'fractionDigits' => 2,
        'numericCode' => '976',
    ),
    'NZD' => array (
        'alphabeticCode' => 'NZD',
        'currencyName' => 'New Zealand Dollar',
        'fractionDigits' => 2,
        'numericCode' => '554',
    ),
    'CRC' => array (
        'alphabeticCode' => 'CRC',
        'currencyName' => 'Costa Rican Colon',
        'fractionDigits' => 2,
        'numericCode' => '188',
    ),
    'HRK' => array (
        'alphabeticCode' => 'HRK',
        'currencyName' => 'Kuna',
        'fractionDigits' => 2,
        'numericCode' => '191',
    ),
    'CUP' => array (
        'alphabeticCode' => 'CUP',
        'currencyName' => 'Cuban Peso',
        'fractionDigits' => 2,
        'numericCode' => '192',
    ),
    'CUC' => array (
        'alphabeticCode' => 'CUC',
        'currencyName' => 'Peso Convertible',
        'fractionDigits' => 2,
        'numericCode' => '931',
    ),
    'ANG' => array (
        'alphabeticCode' => 'ANG',
        'currencyName' => 'Netherlands Antillean Guilder',
        'fractionDigits' => 2,
        'numericCode' => '532',
    ),
    'CZK' => array (
        'alphabeticCode' => 'CZK',
        'currencyName' => 'Czech Koruna',
        'fractionDigits' => 2,
        'numericCode' => '203',
    ),
    'DKK' => array (
        'alphabeticCode' => 'DKK',
        'currencyName' => 'Danish Krone',
        'fractionDigits' => 2,
        'numericCode' => '208',
    ),
    'DJF' => array (
        'alphabeticCode' => 'DJF',
        'currencyName' => 'Djibouti Franc',
        'fractionDigits' => 0,
        'numericCode' => '262',
    ),
    'DOP' => array (
        'alphabeticCode' => 'DOP',
        'currencyName' => 'Dominican Peso',
        'fractionDigits' => 2,
        'numericCode' => '214',
    ),
    'EGP' => array (
        'alphabeticCode' => 'EGP',
        'currencyName' => 'Egyptian Pound',
        'fractionDigits' => 2,
        'numericCode' => '818',
    ),
    'SVC' => array (
        'alphabeticCode' => 'SVC',
        'currencyName' => 'El Salvador Colon',
        'fractionDigits' => 2,
        'numericCode' => '222',
    ),
    'ERN' => array (
        'alphabeticCode' => 'ERN',
        'currencyName' => 'Nakfa',
        'fractionDigits' => 2,
        'numericCode' => '232',
    ),
    'ETB' => array (
        'alphabeticCode' => 'ETB',
        'currencyName' => 'Ethiopian Birr',
        'fractionDigits' => 2,
        'numericCode' => '230',
    ),
    'FKP' => array (
        'alphabeticCode' => 'FKP',
        'currencyName' => 'Falkland Islands Pound',
        'fractionDigits' => 2,
        'numericCode' => '238',
    ),
    'FJD' => array (
        'alphabeticCode' => 'FJD',
        'currencyName' => 'Fiji Dollar',
        'fractionDigits' => 2,
        'numericCode' => '242',
    ),
    'XPF' => array (
        'alphabeticCode' => 'XPF',
        'currencyName' => 'CFP Franc',
        'fractionDigits' => 0,
        'numericCode' => '953',
    ),
    'GMD' => array (
        'alphabeticCode' => 'GMD',
        'currencyName' => 'Dalasi',
        'fractionDigits' => 2,
        'numericCode' => '270',
    ),
    'GEL' => array (
        'alphabeticCode' => 'GEL',
        'currencyName' => 'Lari',
        'fractionDigits' => 2,
        'numericCode' => '981',
    ),
    'GHS' => array (
        'alphabeticCode' => 'GHS',
        'currencyName' => 'Ghana Cedi',
        'fractionDigits' => 2,
        'numericCode' => '936',
    ),
    'GIP' => array (
        'alphabeticCode' => 'GIP',
        'currencyName' => 'Gibraltar Pound',
        'fractionDigits' => 2,
        'numericCode' => '292',
    ),
    'GTQ' => array (
        'alphabeticCode' => 'GTQ',
        'currencyName' => 'Quetzal',
        'fractionDigits' => 2,
        'numericCode' => '320',
    ),
    'GBP' => array (
        'alphabeticCode' => 'GBP',
        'currencyName' => 'Pound Sterling',
        'fractionDigits' => 2,
        'numericCode' => '826',
    ),
    'GNF' => array (
        'alphabeticCode' => 'GNF',
        'currencyName' => 'Guinean Franc',
        'fractionDigits' => 0,
        'numericCode' => '324',
    ),
    'GYD' => array (
        'alphabeticCode' => 'GYD',
        'currencyName' => 'Guyana Dollar',
        'fractionDigits' => 2,
        'numericCode' => '328',
    ),
    'HTG' => array (
        'alphabeticCode' => 'HTG',
        'currencyName' => 'Gourde',
        'fractionDigits' => 2,
        'numericCode' => '332',
    ),
    'HNL' => array (
        'alphabeticCode' => 'HNL',
        'currencyName' => 'Lempira',
        'fractionDigits' => 2,
        'numericCode' => '340',
    ),
    'HKD' => array (
        'alphabeticCode' => 'HKD',
        'currencyName' => 'Hong Kong Dollar',
        'fractionDigits' => 2,
        'numericCode' => '344',
    ),
    'HUF' => array (
        'alphabeticCode' => 'HUF',
        'currencyName' => 'Forint',
        'fractionDigits' => 2,
        'numericCode' => '348',
    ),
    'ISK' => array (
        'alphabeticCode' => 'ISK',
        'currencyName' => 'Iceland Krona',
        'fractionDigits' => 0,
        'numericCode' => '352',
    ),
    'IDR' => array (
        'alphabeticCode' => 'IDR',
        'currencyName' => 'Rupiah',
        'fractionDigits' => 2,
        'numericCode' => '360',
    ),
    'XDR' => array (
        'alphabeticCode' => 'XDR',
        'currencyName' => 'SDR (Special Drawing Right)',
        'fractionDigits' => 0,
        'numericCode' => '960',
    ),
    'IRR' => array (
        'alphabeticCode' => 'IRR',
        'currencyName' => 'Iranian Rial',
        'fractionDigits' => 2,
        'numericCode' => '364',
    ),
    'IQD' => array (
        'alphabeticCode' => 'IQD',
        'currencyName' => 'Iraqi Dinar',
        'fractionDigits' => 3,
        'numericCode' => '368',
    ),
    'ILS' => array (
        'alphabeticCode' => 'ILS',
        'currencyName' => 'New Israeli Sheqel',
        'fractionDigits' => 2,
        'numericCode' => '376',
    ),
    'JMD' => array (
        'alphabeticCode' => 'JMD',
        'currencyName' => 'Jamaican Dollar',
        'fractionDigits' => 2,
        'numericCode' => '388',
    ),
    'JPY' => array (
        'alphabeticCode' => 'JPY',
        'currencyName' => 'Yen',
        'fractionDigits' => 0,
        'numericCode' => '392',
    ),
    'JOD' => array (
        'alphabeticCode' => 'JOD',
        'currencyName' => 'Jordanian Dinar',
        'fractionDigits' => 3,
        'numericCode' => '400',
    ),
    'KZT' => array (
        'alphabeticCode' => 'KZT',
        'currencyName' => 'Tenge',
        'fractionDigits' => 2,
        'numericCode' => '398',
    ),
    'KES' => array (
        'alphabeticCode' => 'KES',
        'currencyName' => 'Kenyan Shilling',
        'fractionDigits' => 2,
        'numericCode' => '404',
    ),
    'KPW' => array (
        'alphabeticCode' => 'KPW',
        'currencyName' => 'North Korean Won',
        'fractionDigits' => 2,
        'numericCode' => '408',
    ),
    'KRW' => array (
        'alphabeticCode' => 'KRW',
        'currencyName' => 'Won',
        'fractionDigits' => 0,
        'numericCode' => '410',
    ),
    'KWD' => array (
        'alphabeticCode' => 'KWD',
        'currencyName' => 'Kuwaiti Dinar',
        'fractionDigits' => 3,
        'numericCode' => '414',
    ),
    'KGS' => array (
        'alphabeticCode' => 'KGS',
        'currencyName' => 'Som',
        'fractionDigits' => 2,
        'numericCode' => '417',
    ),
    'LAK' => array (
        'alphabeticCode' => 'LAK',
        'currencyName' => 'Lao Kip',
        'fractionDigits' => 2,
        'numericCode' => '418',
    ),
    'LBP' => array (
        'alphabeticCode' => 'LBP',
        'currencyName' => 'Lebanese Pound',
        'fractionDigits' => 2,
        'numericCode' => '422',
    ),
    'LSL' => array (
        'alphabeticCode' => 'LSL',
        'currencyName' => 'Loti',
        'fractionDigits' => 2,
        'numericCode' => '426',
    ),
    'ZAR' => array (
        'alphabeticCode' => 'ZAR',
        'currencyName' => 'Rand',
        'fractionDigits' => 2,
        'numericCode' => '710',
    ),
    'LRD' => array (
        'alphabeticCode' => 'LRD',
        'currencyName' => 'Liberian Dollar',
        'fractionDigits' => 2,
        'numericCode' => '430',
    ),
    'LYD' => array (
        'alphabeticCode' => 'LYD',
        'currencyName' => 'Libyan Dinar',
        'fractionDigits' => 3,
        'numericCode' => '434',
    ),
    'CHF' => array (
        'alphabeticCode' => 'CHF',
        'currencyName' => 'Swiss Franc',
        'fractionDigits' => 2,
        'numericCode' => '756',
    ),
    'MOP' => array (
        'alphabeticCode' => 'MOP',
        'currencyName' => 'Pataca',
        'fractionDigits' => 2,
        'numericCode' => '446',
    ),
    'MKD' => array (
        'alphabeticCode' => 'MKD',
        'currencyName' => 'Denar',
        'fractionDigits' => 2,
        'numericCode' => '807',
    ),
    'MGA' => array (
        'alphabeticCode' => 'MGA',
        'currencyName' => 'Malagasy Ariary',
        'fractionDigits' => 2,
        'numericCode' => '969',
    ),
    'MWK' => array (
        'alphabeticCode' => 'MWK',
        'currencyName' => 'Malawi Kwacha',
        'fractionDigits' => 2,
        'numericCode' => '454',
    ),
    'MYR' => array (
        'alphabeticCode' => 'MYR',
        'currencyName' => 'Malaysian Ringgit',
        'fractionDigits' => 2,
        'numericCode' => '458',
    ),
    'MVR' => array (
        'alphabeticCode' => 'MVR',
        'currencyName' => 'Rufiyaa',
        'fractionDigits' => 2,
        'numericCode' => '462',
    ),
    'MRU' => array (
        'alphabeticCode' => 'MRU',
        'currencyName' => 'Ouguiya',
        'fractionDigits' => 2,
        'numericCode' => '929',
    ),
    'MUR' => array (
        'alphabeticCode' => 'MUR',
        'currencyName' => 'Mauritius Rupee',
        'fractionDigits' => 2,
        'numericCode' => '480',
    ),
    'XUA' => array (
        'alphabeticCode' => 'XUA',
        'currencyName' => 'ADB Unit of Account',
        'fractionDigits' => 0,
        'numericCode' => '965',
    ),
    'MXN' => array (
        'alphabeticCode' => 'MXN',
        'currencyName' => 'Mexican Peso',
        'fractionDigits' => 2,
        'numericCode' => '484',
    ),
    'MXV' => array (
        'alphabeticCode' => 'MXV',
        'currencyName' => 'Mexican Unidad de Inversion (UDI)',
        'fractionDigits' => 2,
        'numericCode' => '979',
    ),
    'MDL' => array (
        'alphabeticCode' => 'MDL',
        'currencyName' => 'Moldovan Leu',
        'fractionDigits' => 2,
        'numericCode' => '498',
    ),
    'MNT' => array (
        'alphabeticCode' => 'MNT',
        'currencyName' => 'Tugrik',
        'fractionDigits' => 2,
        'numericCode' => '496',
    ),
    'MAD' => array (
        'alphabeticCode' => 'MAD',
        'currencyName' => 'Moroccan Dirham',
        'fractionDigits' => 2,
        'numericCode' => '504',
    ),
    'MZN' => array (
        'alphabeticCode' => 'MZN',
        'currencyName' => 'Mozambique Metical',
        'fractionDigits' => 2,
        'numericCode' => '943',
    ),
    'MMK' => array (
        'alphabeticCode' => 'MMK',
        'currencyName' => 'Kyat',
        'fractionDigits' => 2,
        'numericCode' => '104',
    ),
    'NAD' => array (
        'alphabeticCode' => 'NAD',
        'currencyName' => 'Namibia Dollar',
        'fractionDigits' => 2,
        'numericCode' => '516',
    ),
    'NPR' => array (
        'alphabeticCode' => 'NPR',
        'currencyName' => 'Nepalese Rupee',
        'fractionDigits' => 2,
        'numericCode' => '524',
    ),
    'NIO' => array (
        'alphabeticCode' => 'NIO',
        'currencyName' => 'Cordoba Oro',
        'fractionDigits' => 2,
        'numericCode' => '558',
    ),
    'NGN' => array (
        'alphabeticCode' => 'NGN',
        'currencyName' => 'Naira',
        'fractionDigits' => 2,
        'numericCode' => '566',
    ),
    'OMR' => array (
        'alphabeticCode' => 'OMR',
        'currencyName' => 'Rial Omani',
        'fractionDigits' => 3,
        'numericCode' => '512',
    ),
    'PKR' => array (
        'alphabeticCode' => 'PKR',
        'currencyName' => 'Pakistan Rupee',
        'fractionDigits' => 2,
        'numericCode' => '586',
    ),
    'PAB' => array (
        'alphabeticCode' => 'PAB',
        'currencyName' => 'Balboa',
        'fractionDigits' => 2,
        'numericCode' => '590',
    ),
    'PGK' => array (
        'alphabeticCode' => 'PGK',
        'currencyName' => 'Kina',
        'fractionDigits' => 2,
        'numericCode' => '598',
    ),
    'PYG' => array (
        'alphabeticCode' => 'PYG',
        'currencyName' => 'Guarani',
        'fractionDigits' => 0,
        'numericCode' => '600',
    ),
    'PEN' => array (
        'alphabeticCode' => 'PEN',
        'currencyName' => 'Sol',
        'fractionDigits' => 2,
        'numericCode' => '604',
    ),
    'PHP' => array (
        'alphabeticCode' => 'PHP',
        'currencyName' => 'Philippine Peso',
        'fractionDigits' => 2,
        'numericCode' => '608',
    ),
    'PLN' => array (
        'alphabeticCode' => 'PLN',
        'currencyName' => 'Zloty',
        'fractionDigits' => 2,
        'numericCode' => '985',
    ),
    'QAR' => array (
        'alphabeticCode' => 'QAR',
        'currencyName' => 'Qatari Rial',
        'fractionDigits' => 2,
        'numericCode' => '634',
    ),
    'RON' => array (
        'alphabeticCode' => 'RON',
        'currencyName' => 'Romanian Leu',
        'fractionDigits' => 2,
        'numericCode' => '946',
    ),
    'RUB' => array (
        'alphabeticCode' => 'RUB',
        'currencyName' => 'Russian Ruble',
        'fractionDigits' => 2,
        'numericCode' => '643',
    ),
    'RWF' => array (
        'alphabeticCode' => 'RWF',
        'currencyName' => 'Rwanda Franc',
        'fractionDigits' => 0,
        'numericCode' => '646',
    ),
    'SHP' => array (
        'alphabeticCode' => 'SHP',
        'currencyName' => 'Saint Helena Pound',
        'fractionDigits' => 2,
        'numericCode' => '654',
    ),
    'WST' => array (
        'alphabeticCode' => 'WST',
        'currencyName' => 'Tala',
        'fractionDigits' => 2,
        'numericCode' => '882',
    ),
    'STN' => array (
        'alphabeticCode' => 'STN',
        'currencyName' => 'Dobra',
        'fractionDigits' => 2,
        'numericCode' => '930',
    ),
    'SAR' => array (
        'alphabeticCode' => 'SAR',
        'currencyName' => 'Saudi Riyal',
        'fractionDigits' => 2,
        'numericCode' => '682',
    ),
    'RSD' => array (
        'alphabeticCode' => 'RSD',
        'currencyName' => 'Serbian Dinar',
        'fractionDigits' => 2,
        'numericCode' => '941',
    ),
    'SCR' => array (
        'alphabeticCode' => 'SCR',
        'currencyName' => 'Seychelles Rupee',
        'fractionDigits' => 2,
        'numericCode' => '690',
    ),
    'SLL' => array (
        'alphabeticCode' => 'SLL',
        'currencyName' => 'Leone',
        'fractionDigits' => 2,
        'numericCode' => '694',
    ),
    'SGD' => array (
        'alphabeticCode' => 'SGD',
        'currencyName' => 'Singapore Dollar',
        'fractionDigits' => 2,
        'numericCode' => '702',
    ),
    'XSU' => array (
        'alphabeticCode' => 'XSU',
        'currencyName' => 'Sucre',
        'fractionDigits' => 0,
        'numericCode' => '994',
    ),
    'SBD' => array (
        'alphabeticCode' => 'SBD',
        'currencyName' => 'Solomon Islands Dollar',
        'fractionDigits' => 2,
        'numericCode' => '90',
    ),
    'SOS' => array (
        'alphabeticCode' => 'SOS',
        'currencyName' => 'Somali Shilling',
        'fractionDigits' => 2,
        'numericCode' => '706',
    ),
    'SSP' => array (
        'alphabeticCode' => 'SSP',
        'currencyName' => 'South Sudanese Pound',
        'fractionDigits' => 2,
        'numericCode' => '728',
    ),
    'LKR' => array (
        'alphabeticCode' => 'LKR',
        'currencyName' => 'Sri Lanka Rupee',
        'fractionDigits' => 2,
        'numericCode' => '144',
    ),
    'SDG' => array (
        'alphabeticCode' => 'SDG',
        'currencyName' => 'Sudanese Pound',
        'fractionDigits' => 2,
        'numericCode' => '938',
    ),
    'SRD' => array (
        'alphabeticCode' => 'SRD',
        'currencyName' => 'Surinam Dollar',
        'fractionDigits' => 2,
        'numericCode' => '968',
    ),
    'SZL' => array (
        'alphabeticCode' => 'SZL',
        'currencyName' => 'Lilangeni',
        'fractionDigits' => 2,
        'numericCode' => '748',
    ),
    'SEK' => array (
        'alphabeticCode' => 'SEK',
        'currencyName' => 'Swedish Krona',
        'fractionDigits' => 2,
        'numericCode' => '752',
    ),
    'CHE' => array (
        'alphabeticCode' => 'CHE',
        'currencyName' => 'WIR Euro',
        'fractionDigits' => 2,
        'numericCode' => '947',
    ),
    'CHW' => array (
        'alphabeticCode' => 'CHW',
        'currencyName' => 'WIR Franc',
        'fractionDigits' => 2,
        'numericCode' => '948',
    ),
    'SYP' => array (
        'alphabeticCode' => 'SYP',
        'currencyName' => 'Syrian Pound',
        'fractionDigits' => 2,
        'numericCode' => '760',
    ),
    'TWD' => array (
        'alphabeticCode' => 'TWD',
        'currencyName' => 'New Taiwan Dollar',
        'fractionDigits' => 2,
        'numericCode' => '901',
    ),
    'TJS' => array (
        'alphabeticCode' => 'TJS',
        'currencyName' => 'Somoni',
        'fractionDigits' => 2,
        'numericCode' => '972',
    ),
    'TZS' => array (
        'alphabeticCode' => 'TZS',
        'currencyName' => 'Tanzanian Shilling',
        'fractionDigits' => 2,
        'numericCode' => '834',
    ),
    'THB' => array (
        'alphabeticCode' => 'THB',
        'currencyName' => 'Baht',
        'fractionDigits' => 2,
        'numericCode' => '764',
    ),
    'TOP' => array (
        'alphabeticCode' => 'TOP',
        'currencyName' => 'Pa’anga',
        'fractionDigits' => 2,
        'numericCode' => '776',
    ),
    'TTD' => array (
        'alphabeticCode' => 'TTD',
        'currencyName' => 'Trinidad and Tobago Dollar',
        'fractionDigits' => 2,
        'numericCode' => '780',
    ),
    'TND' => array (
        'alphabeticCode' => 'TND',
        'currencyName' => 'Tunisian Dinar',
        'fractionDigits' => 3,
        'numericCode' => '788',
    ),
    'TRY' => array (
        'alphabeticCode' => 'TRY',
        'currencyName' => 'Turkish Lira',
        'fractionDigits' => 2,
        'numericCode' => '949',
    ),
    'TMT' => array (
        'alphabeticCode' => 'TMT',
        'currencyName' => 'Turkmenistan New Manat',
        'fractionDigits' => 2,
        'numericCode' => '934',
    ),
    'UGX' => array (
        'alphabeticCode' => 'UGX',
        'currencyName' => 'Uganda Shilling',
        'fractionDigits' => 0,
        'numericCode' => '800',
    ),
    'UAH' => array (
        'alphabeticCode' => 'UAH',
        'currencyName' => 'Hryvnia',
        'fractionDigits' => 2,
        'numericCode' => '980',
    ),
    'AED' => array (
        'alphabeticCode' => 'AED',
        'currencyName' => 'UAE Dirham',
        'fractionDigits' => 2,
        'numericCode' => '784',
    ),
    'USN' => array (
        'alphabeticCode' => 'USN',
        'currencyName' => 'US Dollar (Next day)',
        'fractionDigits' => 2,
        'numericCode' => '997',
    ),
    'UYU' => array (
        'alphabeticCode' => 'UYU',
        'currencyName' => 'Peso Uruguayo',
        'fractionDigits' => 2,
        'numericCode' => '858',
    ),
    'UYI' => array (
        'alphabeticCode' => 'UYI',
        'currencyName' => 'Uruguay Peso en Unidades Indexadas (UI)',
        'fractionDigits' => 0,
        'numericCode' => '940',
    ),
    'UYW' => array (
        'alphabeticCode' => 'UYW',
        'currencyName' => 'Unidad Previsional',
        'fractionDigits' => 4,
        'numericCode' => '927',
    ),
    'UZS' => array (
        'alphabeticCode' => 'UZS',
        'currencyName' => 'Uzbekistan Sum',
        'fractionDigits' => 2,
        'numericCode' => '860',
    ),
    'VUV' => array (
        'alphabeticCode' => 'VUV',
        'currencyName' => 'Vatu',
        'fractionDigits' => 0,
        'numericCode' => '548',
    ),
    'VES' => array (
        'alphabeticCode' => 'VES',
        'currencyName' => 'Bolívar Soberano',
        'fractionDigits' => 2,
        'numericCode' => '928',
    ),
    'VND' => array (
        'alphabeticCode' => 'VND',
        'currencyName' => 'Dong',
        'fractionDigits' => 0,
        'numericCode' => '704',
    ),
    'YER' => array (
        'alphabeticCode' => 'YER',
        'currencyName' => 'Yemeni Rial',
        'fractionDigits' => 2,
        'numericCode' => '886',
    ),
    'ZMW' => array (
        'alphabeticCode' => 'ZMW',
        'currencyName' => 'Zambian Kwacha',
        'fractionDigits' => 2,
        'numericCode' => '967',
    ),
    'ZWL' => array (
        'alphabeticCode' => 'ZWL',
        'currencyName' => 'Zimbabwe Dollar',
        'fractionDigits' => 2,
        'numericCode' => '932',
    ),
    'XBA' => array (
        'alphabeticCode' => 'XBA',
        'currencyName' => 'Bond Markets Unit European Composite Unit (EURCO)',
        'fractionDigits' => 0,
        'numericCode' => '955',
    ),
    'XBB' => array (
        'alphabeticCode' => 'XBB',
        'currencyName' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
        'fractionDigits' => 0,
        'numericCode' => '956',
    ),
    'XBC' => array (
        'alphabeticCode' => 'XBC',
        'currencyName' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
        'fractionDigits' => 0,
        'numericCode' => '957',
    ),
    'XBD' => array (
        'alphabeticCode' => 'XBD',
        'currencyName' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
        'fractionDigits' => 0,
        'numericCode' => '958',
    ),
    'XTS' => array (
        'alphabeticCode' => 'XTS',
        'currencyName' => 'Codes specifically reserved for testing purposes',
        'fractionDigits' => 0,
        'numericCode' => '963',
    ),
    'XXX' => array (
        'alphabeticCode' => 'XXX',
        'currencyName' => 'The codes assigned for transactions where no currencyName is involved',
        'fractionDigits' => 0,
        'numericCode' => '999',
    ),
    'XAU' => array (
        'alphabeticCode' => 'XAU',
        'currencyName' => 'Gold',
        'fractionDigits' => 0,
        'numericCode' => '959',
    ),
    'XPD' => array (
        'alphabeticCode' => 'XPD',
        'currencyName' => 'Palladium',
        'fractionDigits' => 0,
        'numericCode' => '964',
    ),
    'XPT' => array (
        'alphabeticCode' => 'XPT',
        'currencyName' => 'Platinum',
        'fractionDigits' => 0,
        'numericCode' => '962',
    ),
    'XAG' => array (
        'alphabeticCode' => 'XAG',
        'currencyName' => 'Silver',
        'fractionDigits' => 0,
        'numericCode' => '961',
    ),
);
